site_name: Rasa NLU Examples
extra_css: [style.css]
repo_url: https://github.com/RasaHQ/rasa-nlu-examples
site_url: https://rasahq.github.io/rasa-nlu-examples/
site_description: A collection of open source Rasa compatible NLU components.
site_author: Vincent D. Warmerdam @ Rasa Research

nav:
  - Home: index.md
  - Usage:
      - Benchmarking Guide: benchmarking.md
      - Tokenizers:
          - BlankSpacyTokenizer: docs/tokenizer/spacy-tokenizer.md
          - ThaiTokenizer: docs/tokenizer/thai-tokenizer.md
      - Featurizers:
        - BytePairFeaturizer: docs/featurizer/bytepair.md
        - HashingFeaturizer: docs/featurizer/hashing.md
        - TfIdfFeaturizer: docs/featurizer/tfidf.md
        - FastTextFeaturizer: docs/featurizer/fasttext.md
        - GensimFeaturizer: docs/featurizer/gensim.md
      - Intent Classifiers:
        - SparseNaiveBayes: docs/classifier/naive-bayes.md
        - LogisticRegression: docs/classifier/logistic-regression.md
      - Entity Extractors:
        - FlashText: docs/extractors/flashtext.md
        - DateParser: docs/extractors/dateparser.md
  - Contributing:
    - Contribute: contributing.md
plugins:
  - search
  - mkdocstrings:
      watch:
        - rasa_nlu_examples
copyright: Copyright &copy; 2020 <a href="https://twitter.com/Rasa_HQ">Rasa</a>
theme:
  name: material
  features:
    - tabs
    - instant
  palette:
    primary: deep purple
    accent: purple
markdown_extensions:
  - codehilite
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true
